### ISSUE TITLE
[BUG] Uncaught exception when searching

### ISSUE THREAD

**Issue by BachoSeven** [karlch/vimiv-qt#374]
This happens in library mode, when I press `/` to open the search prompt and type any letter. The only notable thing inside the folder in which this happens is the the `4k` folder contains a bunch of symlinks, and two files starting with the `!` character. Tell me if you need more info.

OS: ArchLinux
vimiv-qt version: `r2162.b4b7772f`

``` python
[18:49:37] ERROR    <vimiv>              Uncaught exception! Exiting gracefully and printing stack...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vimiv/gui/commandline.py", line 137, in _incremental_search
    search.search(text, self.mode, reverse=prefix == "?", incremental=True)
  File "/usr/lib/python3.9/site-packages/vimiv/commands/search.py", line 71, in __call__
    self._run(text, mode, count, reverse, incremental)
  File "/usr/lib/python3.9/site-packages/vimiv/commands/search.py", line 89, in _run
    current_index = paths.index(api.current_path(mode))
ValueError: '/mnt/01D5707D40B081F0/Users/ascol/Pictures/papes/4k' is not in list
```

**Comment by karlch** [comment]
Thanks for the report!

Unfortunately I have not been able to reproduce the crash just by adding a few symlinks or files starting with the `!` character to a clean directory and starting a search. Would it be possible for you to reproduce this from an empty directory and record the steps needed to create this directory which causes the crash?

**Comment by BachoSeven** [comment]
Steps: 
- create a directory `mkdir test`
- make a symlink of it: `ln -s test testln`
- create a folder named `4k` inside of it: `cd testln && mkdir 4k && cd ..`
- `vimiv`, then navigate inside `testln` and then press `/` followed by any character
- > Crashes

**Comment by karlch** [comment]
Thanks a lot for this detailed report, I can now reproduce this fine and believe I undersand the issue.

When vimiv enters `testln` we truly enter `test` and this is also what `os.getcwd` / `os.path.abspath` and friends will return. The filelist vimiv populates is however a simple line along `os.path.join("testln", "4k")`. This ultimatley results in the current path `test/4k` not existing in the filelist which only knows `testln/4k`.

The quick solution I can see is replacing `os.path.abspath` with `os.path.realpath` when appropriate. Changing only the `listdir` function in `vimiv.utils.files` to
```python
    directory = os.path.realpath(os.path.expanduser(directory))
    return sorted(
        os.path.join(directory, path)
        for path in os.listdir(directory)
        if show_hidden or not path.startswith(".")
    )
```
fixes the crash for me. But I would like to take some more time to see the actual implications of this all over the source code and checking if we need to switch to realpath also in other places.

**Comment by karlch** [comment]
This should be fixed with the latest commits, let me know if I messed up :laughing:

**Comment by BachoSeven** [comment]
@karlch I just pulled the latest commits but the crash is still present here, same error as above

**Comment by karlch** [comment]
Now this is interesting. I just did a new `git clone` and launched vimiv from the latest master using `python -m vimiv /tmp` where I have your explained directory structure setup in `/tmp`. No crash in `master`.

When I proceed to revert the commits, e.g. by checking out `HEAD~3`, I can reproduce the crash again just fine...

**Comment by BachoSeven** [comment]
I installed it from `aur`(vimiv-qt-git package); however I can also reproduce by:
- uninstalling any vimiv package present on the system
- `git clone` this repo
- install just `python-pyqt5` 
- `python -m vimiv ~` (and the 4k dir is inside a subdir)
- creash

**Comment by karlch** [comment]
Somehow I am too stupid to reproduce... I have attached a quick screencast of what I do (I had to download it, the github player didn't work for me). On the left you can see the basic setup:
- Directory as listed by `tree`
- Vimiv version, i.e. fresh clone with the latest commits

On the right you can see what I do in vimiv:
- First open vimiv within the directory that has both `test` and `testln`
- Then enter `testln`
- Then press `/` to start a search
- Press a few random keys, nothing happens
- Move around a bit, repeat the search and keypress, nothing happens :disappointed:

Maybe you can see what I am missing? :blush: 

https://user-images.githubusercontent.com/12006766/116241746-89c72f80-a765-11eb-87f9-259ff6c1b1d3.mp4

**Comment by jcjgraf** [comment]
I cannot reproduce the crash either anymore.

**Comment by BachoSeven** [comment]
Okay so by doing what you said above, I cannot indeed reproduce(i.e. it's solved)
However in my setup:
`~/pics/papes/4k`, where `papes` is a symlink to a folder on an external ssd disk, still crashes. I am trying to figure out what could be different about it.

**Comment by karlch** [comment]
Thanks for this additional information, I will try to take a closer look at this as well. Reopening for further debugging :blush:

**Comment by jcjgraf** [comment]
@karlch Your changes in 0cc23632 introduce a undesired bug - now vimiv lists symlinks as well as the original image in thumbnail view.

#### Reproduce
- Consider:

```
|- Dir/
   |- a.jpg
   |- Dir/
      |- b.jpg -> ../a.jpg
```

- Open `Dir/Dir`
- Switch to thumbnail view

#### Expected Behaviour
Vimiv shows a single image named `b.jpg`

#### Actual Behaviour
Vimiv shows two images, names `a.jpg` and `b.jpg` respectively

**Comment by karlch** [comment]
Thanks @jcjgraf for catching this! This is indeed a nasty bug. I followed your recommendation in reverting the commit, but also tried to fix the issue that it attempted to solve, in #397. Maybe you could give this a shot before I merge it? :blush:
